Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import numpy as np
squaremeter = np.array([100,150,125,142,155,178,200,95,90,120])
rooms = np.array([3,4,3,5,5,6,7,2,2,3])
price = np.array([350000,450000,125000,360000,415000,750000,1000000,2500000,200000,350000])
all_features = np.array([squaremeter,rooms,price])
print(all_features)

[[    100     150     125     142     155     178     200      95      90
      120]
 [      3       4       3       5       5       6       7       2       2
        3]
 [ 350000  450000  125000  360000  415000  750000 1000000 2500000  200000
   350000]]


Transpose the array you have created, so that every line can represent features of one house.

In [2]:
new_all_features= all_features.transpose()
print(new_all_features)

[[    100       3  350000]
 [    150       4  450000]
 [    125       3  125000]
 [    142       5  360000]
 [    155       5  415000]
 [    178       6  750000]
 [    200       7 1000000]
 [     95       2 2500000]
 [     90       2  200000]
 [    120       3  350000]]


Display the shape of the array and explain what it means.

In [4]:
new_all_features.shape     # (10,3) olmasının sebebi 10 satır ve 3 sütun içeren 2 boyutlu bir matris olmasıdır.

(10, 3)

Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

In [5]:
def shape_matrix(x,y):
  a = np.ones((x,y))
  a[1:y+1:2,1:x+1:2]=0
  print(a)
shape_matrix(6,5)

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
